# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.setting_action = QtWidgets.QAction(MainWindow)
        self.setting_action.setObjectName("setting_action")
        self.add_action = QtWidgets.QAction(MainWindow)
        self.add_action.setObjectName("add_action")
        self.refresh_action = QtWidgets.QAction(MainWindow)
        self.refresh_action.setObjectName("refresh_action")
        self.del_action = QtWidgets.QAction(MainWindow)
        self.del_action.setObjectName("del_action")
        self.toolBar.addAction(self.setting_action)
        self.toolBar.addAction(self.del_action)
        self.toolBar.addAction(self.refresh_action)
        self.toolBar.addAction(self.add_action)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.setting_action.setText(_translate("MainWindow", "设置"))
        self.add_action.setText(_translate("MainWindow", "新增"))
        self.refresh_action.setText(_translate("MainWindow", "刷新"))
        self.del_action.setText(_translate("MainWindow", "删除"))
